FROM python:3.9-buster

ENV LANG C.UTF-8
ENV TZ UTC
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /backend/app:/backend
ENV TERM xterm-256color
# EXPOSE 80

RUN apt-get update && apt-get install -y \
    git \
    gcc \
    libmariadb-dev \
    curl
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false


WORKDIR ${LAMBDA_TASK_ROOT}/backend
COPY ./pyproject.toml ./poetry.lock ${LAMBDA_TASK_ROOT}/backend/
COPY ./app/main.py ${LAMBDA_TASK_ROOT}

RUN echo ${LAMBDA_TASK_ROOT}
RUN poetry install --no-root
RUN pip install awslambdaric

COPY . ${LAMBDA_TASK_ROOT}/backend/

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD ["app.main.handler"]
