ARG FUNCTION_DIR="/function"
FROM python:3.9-buster

ENV LANG C.UTF-8
ENV TZ UTC
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH ${FUNCTION_DIR}/backend
ENV TERM xterm-256color
# EXPOSE 80

RUN apt-get update && apt-get install -y \
    git \
    gcc \
    libmariadb-dev \
    curl
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Create function directory
RUN mkdir -p ${FUNCTION_DIR}
WORKDIR ${FUNCTION_DIR}/backend
COPY ./pyproject.toml ./poetry.lock ${FUNCTION_DIR}/backend/

RUN poetry install --no-root
RUN pip install awslambdaric

COPY . ${FUNCTION_DIR}/backend/

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD ["app/main.handler"]
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
