"""empty message

Revision ID: 338ff834870e
Revises: e4b9622be822
Create Date: 2022-03-25 00:05:56.164475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338ff834870e'
down_revision = 'e4b9622be822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
