"""empty message

Revision ID: d4e0991b49d5
Revises: 28b2ddd52e6e
Create Date: 2022-05-11 14:34:34.161157

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d4e0991b49d5"
down_revision = "28b2ddd52e6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_jobs",
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.create_index(op.f("ix_user_jobs_job_id"), "user_jobs", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_user_jobs_user_id"), "user_jobs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_jobs_user_id"), table_name="user_jobs")
    op.drop_index(op.f("ix_user_jobs_job_id"), table_name="user_jobs")
    op.drop_table("user_jobs")
    # ### end Alembic commands ###
