"""empty message

Revision ID: 6d4151b10c3e
Revises: 5d2779598260
Create Date: 2022-03-22 22:53:12.719557

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6d4151b10c3e"
down_revision = "5d2779598260"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("jobs", "deleted_at")
    # ### end Alembic commands ###
