/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI Sample
 * Apps link<br>/docs<br><a href=\'/admin/docs\'>/admin/docs</a><br><a href=\'/other/docs\'>/other/docs</a>
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
